Api home work
Nikolajml/TMS_TestRail_API pull request #1
Opened 2023-06-10 07:44 UTC by Nikolajml

2023-06-13 05:17 UTC, wildpioneer requested changes

2023-06-13 05:17 UTC, wildpioneer commented on TAF_TMS_C1onl/TAF_TMS_C1onl/Services/ProjectService.cs
> +    public RestResponse AddProjectForMileson(Project someProject)
А проект мы только для Milestone может создавать? Для чего это уточнение в названии?

2023-06-13 05:17 UTC, wildpioneer commented on TAF_TMS_C1onl/TAF_TMS_C1onl/Tests/API/CaseTest.cs
> +        // I DON'T UNDERTAND WHY THIS TEST IS FAILED???
У меня ничего не упало - а с какой ошибкой падает у тебя?

2023-06-13 15:41 UTC, Nikolajml commented on TAF_TMS_C1onl/TAF_TMS_C1onl/Services/ProjectService.cs
> +    public RestResponse AddProjectForMileson(Project someProject)
Согласен, не логично с моей стороны.

2023-06-13 15:42 UTC, Nikolajml commented on TAF_TMS_C1onl/TAF_TMS_C1onl/Tests/API/CaseTest.cs
> +        // I DON'T UNDERTAND WHY THIS TEST IS FAILED???
Запустил сегодня эти тесты и все прошли. Так и не понял, в чем была проблема, но теперь все работает.

2023-07-02 18:09 UTC, closed without merging

2023-07-02 18:09 UTC, wildpioneer commented
Проверено